### ISSUE TITLE
Disk missed since Update 1.4.1 (x86)

### ISSUE THREAD

**Issue by mseidler79** [IceWhaleTech/ZimaOS#222]
Since update to version 1.4.1 the disks used in a RAID5 a reported as "Disk missed".
Storage is available and working but display in settings is faulty.

**Comment by mseidler79** [comment]
![Image](https://github.com/user-attachments/assets/79f60290-d15d-445b-8f16-1597fef79a37)

**Comment by serycoola** [comment]
Have you tried rebooting the system? If you say that the storage is working, it means that there might be a problem only with the way the settings panel has failed to initialize. I had a similar problem once, with an older update. Rebooting the system fixed the issue.

**Comment by mseidler79** [comment]
A reboot was not solving the usuelle. I also Gries to break the raid and rebuild it. After the rebuild process, the disks are still schön as Disk missed.

**Comment by mseidler79** [comment]
In Beta 2 the Problem was Not existent.

**Comment by ghost** [comment]
I have the same problem. It has a Ziemablade 7700 on board. Two new WD Red Pro drives. Zimaos 1.4.1. RAID 1 system. It keeps losing a hard drive. Rebooting doesn't help. This happens sporadically. Sometimes it works, sometimes the hard drive gets lost.

**Comment by mseidler79** [comment]
@Ecotom83 in my case the SSDs are not lost, they only don't show any information. If I break the Raid they are visible. So I think the issue is related to the MDADM and the SMARTCTL.

**Comment by ghost** [comment]
Yes, that makes sense. After I finished copying my data, rebooted, and let the system run without any interference, a new error occurred three days later. The HDD was mounted in RAID 1, but at the same time, it was displayed as a newly discovered HDD. A reboot resolved this error. Can I hope for improvement after the next update, or is there a solution? Excuse my English; it's from Google Translate.

**Comment by mseidler79** [comment]
Problem still occurs in 1.4.2 Beta1

**Comment by DuEyE** [comment]
Yes. In my case IT seems Like all the Data is gone. It tells me that I should create a RAID and each disk ist empty.

**Comment by amirburbea** [comment]
Happens in 1.4.2-beta2 as well.

I ran `cat /proc/mdstat` and md0 shows as [UUUU] but in zimaOS storage view it says 2 of my four raid disks are missing.

**Comment by mseidler79** [comment]
Can confirm that it is still happening in 1.4.2 beta2. Disk still missed. But smart values like temperatures are now visible.

![Image](https://github.com/user-attachments/assets/f425d396-49ad-4ebf-86d7-532c6bfdf558)

By the way, after the upgrade I broke the raid and set it up again. No difference.

**Comment by mseidler79** [comment]
Problem still exsits on 1.4.3.

**Comment by mseidler79** [comment]
Fixed with 1.4.4!

**Comment by noahbleau** [comment]
Problem still exist on 1.6.0-beta2. UI says it's missing but still working correctly in file browser.

<img width="1279" height="830" alt="Image" src="https://github.com/user-attachments/assets/f4e07c25-7123-4031-a03b-65d8b21da5a9" />

<img width="953" height="231" alt="Image" src="https://github.com/user-attachments/assets/7cb85f4d-76f2-4326-a916-cf47d3ed0b29" />
